language: csharp
# get dotnet 3.0 preview:
#   https://travis-ci.community/t/net-core-3-0-preview/1936/6
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
solution: Pastdev.Logging.Xunit.sln
mono: none
script:
- sudo snap alias dotnet-sdk.dotnet dotnet
- dotnet --version
- dotnet build
